In [1]:
pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
import pandas as pd


In [4]:
data=pd.read_csv('tested.csv')

In [5]:
print("the rows and columns are",data.shape)


the rows and columns are (418, 12)


In [6]:
data.head(10)




PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   
7          899         0       2   
8          900         1       3   
9          901         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1   
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0      0   
9                       Davies, Mr. John Samuel    male  21.0      2      0   

      Ticket     Fare Cabin Embarked  
0     330911   7.8292   NaN        Q  
1     363272   7.0000   NaN        S  
2     240276   9.6875   NaN        Q  
3     315154   8.6625   NaN        S  
4    3101298  12.2875   NaN        S  
5       7538   9.2250   NaN        S  
6     330972   7.6292   NaN        Q  
7     248738  29.0000   NaN        S  
8       2657   7.2292   NaN        C  
9  A/4 48871  24.1500   NaN        S

In [7]:
data.head(10)

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   
7          899         0       2   
8          900         1       3   
9          901         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1   
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0      0   
9                       Davies, Mr. John Samuel    male  21.0      2      0   

      Ticket     Fare Cabin Embarked  
0     330911   7.8292   NaN        Q  
1     363272   7.0000   NaN        S  
2     240276   9.6875   NaN        Q  
3     315154   8.6625   NaN        S  
4    3101298  12.2875   NaN        S  
5       7538   9.2250   NaN        S  
6     330972   7.6292   NaN        Q  
7     248738  29.0000   NaN        S  
8       2657   7.2292   NaN        C  
9  A/4 48871  24.1500   NaN        S

In [8]:
adata=data.head(10)
bdata=data.tail(10)
pd.concat([adata,bdata])


PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
5            897         0       3   
6            898         1       3   
7            899         0       2   
8            900         1       3   
9            901         0       3   
408         1300         1       3   
409         1301         1       3   
410         1302         1       3   
411         1303         1       1   
412         1304         1       3   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                                Name     Sex   Age  SibSp  \
0                                   Kelly, Mr. James    male  34.5      0   
1                   Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2                          Myles, Mr. Thomas Francis    male  62.0      0   
3                                   Wirz, Mr. Albert    male  27.0      0   
4       Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1   
5                         Svensson, Mr. Johan Cervin    male  14.0      0   
6                               Connolly, Miss. Kate  female  30.0      0   
7                       Caldwell, Mr. Albert Francis    male  26.0      1   
8          Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0   
9                            Davies, Mr. John Samuel    male  21.0      2   
408                  Riordan, Miss. Johanna Hannah""  female   NaN      0   
409                        Peacock, Miss. Treasteall  female   3.0      1   
410                           Naughton, Miss. Hannah  female   NaN      0   
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
412                   Henriksson, Miss. Jenny Lovisa  female  28.0      0   
413                               Spector, Mr. Woolf    male   NaN      0   
414                     Oliva y Ocana, Dona. Fermina  female  39.0      0   
415                     Saether, Mr. Simon Sivertsen    male  38.5      0   
416                              Ware, Mr. Frederick    male   NaN      0   
417                         Peter, Master. Michael J    male   NaN      1   

     Parch              Ticket      Fare Cabin Embarked  
0        0              330911    7.8292   NaN        Q  
1        0              363272    7.0000   NaN        S  
2        0              240276    9.6875   NaN        Q  
3        0              315154    8.6625   NaN        S  
4        1             3101298   12.2875   NaN        S  
5        0                7538    9.2250   NaN        S  
6        0              330972    7.6292   NaN        Q  
7        1              248738   29.0000   NaN        S  
8        0                2657    7.2292   NaN        C  
9        0           A/4 48871   24.1500   NaN        S  
408      0              334915    7.7208   NaN        Q  
409      1  SOTON/O.Q. 3101315   13.7750   NaN        S  
410      0              365237    7.7500   NaN        Q  
411      0               19928   90.0000   C78        Q  
412      0              347086    7.7750   NaN        S  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C

In [9]:
print("mean of all columns is:",data.mean())


mean of all columns is: PassengerId    1100.500000
Survived          0.363636
Pclass            2.265550
Age              30.272590
SibSp             0.447368
Parch             0.392344
Fare             35.627188
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


In [10]:
print("median is:",data.median())

median is: PassengerId    1100.5000
Survived          0.0000
Pclass            3.0000
Age              27.0000
SibSp             0.0000
Parch             0.0000
Fare             14.4542
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


In [11]:
data.sort_values(by="Fare", ascending=False)

PassengerId  Survived  Pclass  \
343         1235         1       1   
53           945         1       1   
69           961         1       1   
24           916         1       1   
142         1034         0       1   
..           ...       ...     ...   
133         1025         0       3   
21           913         0       3   
266         1158         0       1   
372         1264         0       1   
152         1044         0       3   

                                                  Name     Sex   Age  SibSp  \
343  Cardeza, Mrs. James Warburton Martinez (Charlo...  female  58.0      0   
53                          Fortune, Miss. Ethel Flora  female  28.0      3   
69                 Fortune, Mrs. Mark (Mary McDougald)  female  60.0      1   
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  48.0      1   
142                         Ryerson, Mr. Arthur Larned    male  61.0      1   
..                                                 ...     ...   ...    ...   
133                              Thomas, Mr. Charles P    male   NaN      1   
21                           Olsen, Master. Artur Karl    male   9.0      0   
266              Chisholm, Mr. Roderick Robert Crispin    male   NaN      0   
372                            Ismay, Mr. Joseph Bruce    male  49.0      0   
152                                 Storey, Mr. Thomas    male  60.5      0   

     Parch    Ticket      Fare            Cabin Embarked  
343      1  PC 17755  512.3292      B51 B53 B55        C  
53       2     19950  263.0000      C23 C25 C27        S  
69       4     19950  263.0000      C23 C25 C27        S  
24       3  PC 17608  262.3750  B57 B59 B63 B66        C  
142      3  PC 17608  262.3750  B57 B59 B63 B66        C  
..     ...       ...       ...              ...      ...  
133      0      2621    6.4375              NaN        C  
21       1   C 17368    3.1708              NaN        S  
266      0    112051    0.0000              NaN        S  
372      0    112058    0.0000      B52 B54 B56        S  
152      0      3701       NaN              NaN        S  

[418 rows x 12 columns]

In [12]:
data.isnull()


PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
413        False     False   False  False  False   True  False  False   False   
414        False     False   False  False  False  False  False  False   False   
415        False     False   False  False  False  False  False  False   False   
416        False     False   False  False  False   True  False  False   False   
417        False     False   False  False  False   True  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False   True     False  
2    False   True     False  
3    False   True     False  
4    False   True     False  
..     ...    ...       ...  
413  False   True     False  
414  False  False     False  
415  False   True     False  
416  False   True     False  
417  False   True     False  

[418 rows x 12 columns]

In [13]:
print("to drop column with null value",data.dropna(1))

to drop column with null value      PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex  SibSp  Parch  \
0                                Kelly, Mr. James    male      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female      1      0   
2                       Myles, Mr. Thomas Francis    male      0      0   
3                                Wirz, Mr. Albert    male      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female      1      1   
..                                            ...     ...    .

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only
  """Entry point for launching an IPython kernel.


In [14]:
data.dropna()

PassengerId  Survived  Pclass  \
12           904         1       1   
14           906         1       1   
24           916         1       1   
26           918         1       1   
28           920         0       1   
..           ...       ...     ...   
404         1296         0       1   
405         1297         0       2   
407         1299         0       1   
411         1303         1       1   
414         1306         1       1   

                                                  Name     Sex   Age  SibSp  \
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1   
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  48.0      1   
26                        Ostby, Miss. Helene Ragnhild  female  22.0      0   
28                             Brady, Mr. John Bertram    male  41.0      0   
..                                                 ...     ...   ...    ...   
404                       Frauenthal, Mr. Isaac Gerald    male  43.0      1   
405       Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0   
407                         Widener, Mr. George Dunton    male  50.0      1   
411    Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
414                       Oliva y Ocana, Dona. Fermina  female  39.0      0   

     Parch         Ticket      Fare            Cabin Embarked  
12       0          21228   82.2667              B45        S  
14       0    W.E.P. 5734   61.1750              E31        S  
24       3       PC 17608  262.3750  B57 B59 B63 B66        C  
26       1         113509   61.9792              B36        C  
28       0         113054   30.5000              A21        S  
..     ...            ...       ...              ...      ...  
404      0          17765   27.7208              D40        C  
405      0  SC/PARIS 2166   13.8625              D38        C  
407      1         113503  211.5000              C80        C  
411      0          19928   90.0000              C78        Q  
414      0       PC 17758  108.9000             C105        C  

[87 rows x 12 columns]

In [15]:
Arr1 = np.array([1,2,3,2,3,4,3,4,5,6])



In [16]:
Arr2 = np.array([7,2,10,2,7,4,9,4,9,8])


In [17]:
Arr1_2d = np.reshape(Arr1, (2, 5))
print(Arr1_2d)


[[1 2 3 2 3]
 [4 3 4 5 6]]


In [20]:
np.intersect1d(Arr1,Arr2)

array([2, 4])

In [21]:
print("the elements present in only array1 is:", np.delete(Arr1,[1,3,5,7]))

the elements present in only array1 is: [1 3 3 3 5 6]


In [23]:
set_diff = np.setdiff1d(Arr1, Arr2)
print("the elements present in only array1 is:", set_diff)

the elements present in only array1 is: [1 3 5 6]


In [24]:
np.isnan(Arr1)


array([False, False, False, False, False, False, False, False, False,
       False])